# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'insert something to consume'
        required: true
        default: 'https://qishui.douyin.com/s/iRYawDwb/'
        
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install -r requirements.txt

    - name: setup-inputs
      # You may pin to the exact commit or the version.
      # uses: simenandre/setup-inputs@00a2f5d3135898b400343ff87d99b7841e6e4592
      uses: simenandre/setup-inputs@v1.1.0
      id: inputs
      
    - run: echo ${{ steps.inputs.outputs.url }}
